from sqlalchemy import Column, Integer, String, DateTime, JSON
from sqlalchemy.sql import func
from services.database import Base

class Request(Base):
    """
    Tracks every request made through the proxy for monitoring and debugging.
    Stores both timing metrics and request/response data to help performance analysis.
    """
    __tablename__ = "requests"
    
    # Primary identifier for each request
    id = Column(Integer, primary_key=True, index=True)
    
    # Which fal.ai endpoint was called ("/kontext", "/kontext/max", "/kontext/dev")
    # Required: Enables filtering and comparison of endpoint performance
    endpoint = Column(String, nullable=False)
    
    # Original image URL provided by the user
    # Required: For debugging failed requests and tracking input sources
    input_image_url = Column(String, nullable=False)
    
    # Text prompt provided by the user for image editing
    # Required: For debugging and identifying common prompts/patterns
    prompt = Column(String, nullable=False)
    
    # Array of output image URLs returned by fal.ai (can be multiple images)
    # Stored as JSON to handle variable number of results
    # Optional: Null if request failed before getting results
    output_image_urls = Column(JSON)
    
    # Total time from request start to response (milliseconds)
    # Includes: image download + fal.ai call + result processing
    # Required: Measures user-facing performance (what the user experiences)
    total_response_time = Column(Integer)
    
    # Time spent in fal.ai API call only (milliseconds)
    # Excludes: image download/upload time
    # Required: Identifies if slowness is from fal.ai or our proxy overhead
    fal_api_time = Column(Integer)
    
    # Request outcome: "success" or "failed"
    # Required: For calculating success rates and filtering errors
    status = Column(String)
    
    # Error message if request failed (null on success)
    # Optional: Only populated when status = "failed"
    # Used for: Debugging and identifying common failure patterns
    error_message = Column(String, nullable=True)
    
    # Timestamp when request was received
    # Auto-generated by database on insert
    # Required: For time-series analysis and tracking usage patterns
    created_at = Column(DateTime(timezone=True), server_default=func.now())